### PR TITLE
enable short bool options for list and backup commands

### PR DESCRIPTION
**Pull request by liquuid**

### CODE REVIEW

**Comment by Dilshat** [comment]
Does this PR consider the caution from here https://github.com/urfave/cli#combining-short-bool-options
namely:
```If you enable the *UseShortOptionHandling, then you must not use any flags that have a single leading - or this will result in failures. For example, -option can no longer be used. Flags with two leading dashes (such as --options) are still valid.```

**Comment by liquuid** [comment]
We have a problem, in the help message export and backup is said that the options are: two leading dashes + full name  or  single leading dash + letter. But simple leading dash + full name also worked. On this PR  simple leading dash + full name don't work anymore.  So, the problem don't have a solution :-(

**Comment by akarasulu** [comment]
These commands are an API. Other things use them. Make sure this does not result in breakage before deploying them. At least great the code bases to make sure we're not using old versions of changes are no longer compatible.

**Comment by Dilshat** [comment]
Closed for now until we make sure this does not break API and clients operation

**Pull request closed without merging**
